### ISSUE TITLE
Official Extension List

### ISSUE THREAD

**Issue by RyanBayne** [RyanBayne/TwitchPress#112]
This is a list of extensions that I intend to create. See the [Extensions Wiki](https://github.com/RyanBayne/TwitchPress/wiki/Extensions) page for more information. 

- [x] Ultimate Member - Change user role based on Twitch subscription plan. 
- [x] Sync - An extension which focuses on syncing Twitch data so multiple other extension doesn't have to.
- [x] Twitch Login - This extension offers a button for login and registration via Twitch.
- [x] Embed Everything - Display live video and chat on any WordPress post/page or sidebar widget.
- [ ] PayPal API - Allow visitors to buy spaces for streaming their own channel.  
- [ ] DeepBot API - #190 
- [ ] Streamtip - #189 
- [ ] Discord API - #188 
- [ ] Streamlabs API - #187  
- [ ] Subscriber Management - View data about your channels subscribers. 
- [ ] Patreon.com API - Add that Patreon only layer with integration throughout WordPress.
- [ ] Two Streamer Layout - #183   
- [ ] IRC Chat Bot - An extension for those with a good server. We can use the power of WP to bring more control over chat and add more to it.
- [ ] Bits - The API is limited but we'll allow some bit data viewing within the TwitchPress suite.
- [ ] Games - If you have an idea on how to present game specific data in an interesting way then this will be the extension to help you.
- [ ] Teams - Import some data about your team and display them on your WP. There are endless things we can do to make the presentation of your team suit your site.
- [ ] XBox API - Share XBox content such as achievements with the Twitch feed and chat.
- [ ] Steam API - Share statistics and achievements on WP and Twitch.tv feed or chat.
- [ ] YouTube API - Generate video posts and share the URL in-line with Twitch activity. 
- [ ] Reddit API - wait and see!

**Comment by RyanBayne** [comment]
Add new extension...

> Mass Feed Syncing - TwitchPress has a custom post type for adding channels which can be used by extensions in any way imagined. My own extension will focus on syncing channel feeds.

**Comment by RyanBayne** [comment]
Not many more extensions will be released in 2017. 

I wish to give the core a chance to get ahead. If I do create more extensions they will be strict alpha projects with no goal of finishing them until 2018.  This might be required to explore the API requirements of extensions hooking into the core plugin.

**Comment by gilfy** [comment]
good man!

**Comment by RyanBayne** [comment]
The extensions list will now be managed within the Wiki. 

https://github.com/RyanBayne/TwitchPress/wiki/Extensions
